# Example Travis config. See the entire example: https://github.com/JonathanPorta/ci-build
 
language: objective-c
osx_image: xcode61
rvm:
- 2.1.2
before_install:
- chmod a+x ./scripts/download.sh
- chmod a+x ./scripts/install.sh
install:
- travis_wait sudo installer -dumplog -package Unity.pkg -target /
before_script:
- chmod a+x ./scripts/build.sh
script:
- ./scripts/build.sh